CREATE FUNCTION DBO.YAS_HESAPLA(@BIRTHDATE AS DATE)
RETURNS INT
AS
BEGIN
DECLARE @RESULT AS INT
SET @RESULT = DATEDIFF(YEAR,@BIRTHDATE,GETDATE())
RETURN @RESULT
END

SELECT DBO.YAS_HESAPLA('2002-11-04')